# Generated by Django 4.2.11 on 2024-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('website_link', models.URLField(max_length=80)),
                ('category', models.CharField(choices=[('APP', 'Application'), ('CA', 'Card'), ('WEB', 'Development Web')], max_length=50)),
                ('imageProject', models.ImageField(upload_to='images/projects_images/')),
            ],
        ),
    ]
