# Generated by Django 4.2.11 on 2024-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('word1', models.CharField(max_length=25)),
                ('word2', models.CharField(blank=True, max_length=25)),
                ('word3', models.CharField(blank=True, max_length=25)),
                ('word4', models.CharField(blank=True, max_length=25)),
                ('image', models.ImageField(upload_to='images/hero_images/')),
            ],
        ),
    ]
