# Generated by Django 4.2.11 on 2024-05-03 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsSection_app', '0003_alter_skills_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level_skill',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
