# Generated by Django 4.2.11 on 2024-05-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsSection_app', '0005_alter_skills_profileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='profileID',
        ),
    ]
