# Generated by Django 4.2.11 on 2024-05-06 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.TextField()),
                ('job_title', models.CharField(max_length=60)),
                ('job_title2', models.CharField(blank=True, max_length=60, null=True)),
                ('description_2', models.TextField()),
                ('birthday', models.DateField()),
                ('website', models.URLField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('city', models.CharField(max_length=40)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(67)])),
                ('degree', models.CharField(choices=[('MA', 'Master'), ('BAC', 'Bachelor'), ('SD', 'Secondary diploma'), ('ND', 'No diploma')], max_length=50)),
                ('email', models.EmailField(max_length=54)),
                ('isFreelance', models.BooleanField()),
                ('description_3', models.TextField()),
                ('imageProfile', models.ImageField(upload_to='images/profiles_images/')),
            ],
        ),
    ]
