# Generated by Django 4.2.11 on 2024-05-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('jobTitle', models.CharField(max_length=50)),
                ('jobTitle2', models.CharField(blank=True, max_length=50)),
                ('self_description', models.TextField()),
                ('image', models.ImageField(upload_to='images/testimonial_images/')),
            ],
        ),
    ]
