# Generated by Django 4.2.11 on 2024-05-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonialsSection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='media/images/testimonial_images/'),
        ),
    ]
