# Generated by Django 4.2.11 on 2024-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonialsSection_app', '0002_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='images/testimonial_images/'),
        ),
    ]
